
export interface RuneFragment {
    name: string;
  }
  
  // This structure now represents all available fragments for a given tier.
  export const FRAGMENTS_BY_TIER: Record<number, RuneFragment[]> = {
    2: [
      { name: 'Fragmento da Ira Celestial (Verde)' },
      { name: 'Fragmento da Ira Celestial (Roxo)' },
      { name: 'Fragmento de Artesão (Amarelo)' },
      { name: 'Fragmento de Ataque Poderoso (Amarelo)' },
      { name: 'Fragmento de Congelar (Verde)' },
      { name: 'Fragmento de Congelar (Roxo)' },
      { name: 'Fragmento de Maldição (Verde)' },
      { name: 'Fragmento de Maldição (Roxo)' },
      { name: 'Fragmento de Meteorito (Verde)' },
      { name: 'Fragmento de Meteorito (Roxo)' },
      { name: 'Fragmento de Proteção (Amarelo)' },
      { name: 'Fragmento de Sombra (Amarelo)' },
      { name: 'Fragmento de Transição (Verde)' },
      { name: 'Fragmento de Transição (Roxo)' },
      { name: 'Fragmento do Pântano Venenoso (Verde)' },
      { name: 'Fragmento do Pântano Venenoso (Roxo)' },
      { name: 'Fragmento Inabalável (Amarelo)' },
      { name: 'Fragmento Inócuo (Verde)' },
      { name: 'Fragmento Inócuo (Roxo)' },
      { name: 'Fragmento Venenoso (Verde)' },
      { name: 'Fragmento Venenoso (Roxo)' },
      { name: 'Nenhum Fragmento (Vermelho)' }
    ],
    3: [
      { name: 'Fragmento do Escudo de Veneno (Vermelho)' },
      { name: 'Fragmento do Espaço-Tempo (Vermelho)' },
      { name: 'Fragmento de Substituição (Roxo)' },
      { name: 'Fragmento da Chama Venenosa (Roxo)' },
      { name: 'Fragmento da Ilusão (Roxo)' },
      { name: 'Fragmento de Explosão Venenosa (Roxo)' },
      { name: 'Fragmento da Estrela Cadente (Roxo)' },
      { name: 'Fragmento da Perdição (Roxo)' },
      { name: 'Fragmento de Calor (Roxo)' },
      { name: 'Fragmento do Ceifador (Roxo)' },
      { name: 'Fragmento de Substituição (Verde)' },
      { name: 'Fragmento da Chama Venenosa (Verde)' },
      { name: 'Fragmento da Ilusão (Verde)' },
      { name: 'Fragmento de Explosão Venenosa (Verde)' },
      { name: 'Fragmento da Estrela Cadente (Verde)' },
      { name: 'Fragmento da Perdição (Verde)' },
      { name: 'Fragmento de Calor (Verde)' },
      { name: 'Fragmento do Ceifador (Verde)' },
      { name: 'Fragmento Guardião (Amarelo)' },
      { name: 'Fragmento de Paixão (Amarelo)' },
      { name: 'Fragmento de Transcendência (Amarelo)' },
      { name: 'Fragmento de Golpe Crucial (Amarelo)' },
      { name: 'Fragmento de Justiça (Amarelo)' },
    ],
    4: [
      { name: 'Fragmento do Mensageiro (Vermelho)' },
      { name: 'Fragmento de Separação (Vermelho)' },
      { name: 'Fragmento de Imagem Espelhada (Roxo)' },
      { name: 'Fragmento de Juramento (Roxo)' },
      { name: 'Fragmento de Rastro de Veneno (Roxo)' },
      { name: 'Fragmento de Elemento (Roxo)' },
      { name: 'Fragmento do Penhasco de Gelo (Roxo)' },
      { name: 'Território do Ceifador (Roxo)' },
      { name: 'Fragmento de Congelamento (Roxo)' },
      { name: 'Fragmento de Imagem Espelhada (Verde)' },
      { name: 'Fragmento de Juramento (Verde)' },
      { name: 'Fragmento de Rastro de Veneno (Verde)' },
      { name: 'Fragmento de Elemento (Verde)' },
      { name: 'Fragmento do Penhasco de Gelo (Verde)' },
      { name: 'Território do Ceifador (Verde)' },
      { name: 'Fragmento de Congelamento (Verde)' },
      { name: 'Fragmento de Placa (Amarelo)' },
      { name: 'Fragmento de Integridade (Amarelo)' },
      { name: 'Fragmento de Incursão (Amarelo)' },
      { name: 'Fragmento de Pulso (Amarelo)' },
      { name: 'Fragmento de Reparação (Amarelo)' },
    ],
    5: [
      { name: 'Fragmento de Prazer Perverso (Roxo)' },
      { name: 'Fragmento de Gelo (Roxo)' },
      { name: 'Fragmento de Imagem Espelhada (Roxo)' },
      { name: 'Fragmento da Miragem (Roxo)' },
      { name: 'Fragmento Elemental II (Roxo)' },
      { name: 'Sequelas do Veneno (Roxo)' },
      { name: 'Fragmento do Espinho de Gelo (Roxo)' },
      { name: 'Fragmento do Campo de Neve (Roxo)' },
      { name: 'Fragmento do Inverno Elemental (Roxo)' },
      { name: 'Fragmento de Imagem Espelhada (Verde)' },
      { name: 'Fragmento da Miragem (Verde)' },
      { name: 'Fragmento Elemental II (Verde)' },
      { name: 'Sequelas do Veneno (Verde)' },
      { name: 'Fragmento do Espinho de Gelo (Verde)' },
      { name: 'Fragmento do Campo de Neve (Verde)' },
      { name: 'Fragmento do Inverno Elemental (Verde)' },
      { name: 'Fragmento de Escudo Flexível (Amarelo)' },
      { name: 'Fragmento de Armadura Flexível (Amarelo)' },
      { name: 'Fragmento de Escudo Firme (Amarelo)' },
      { name: 'Fragmento de Peixe de Ferro (Amarelo)' },
      { name: 'Fragmento Base (Amarelo)' },
    ],
    6: [
      { name: 'Fragmento de Iluminação (Roxo)' },
      { name: 'Fragmento de Injeção (Roxo)' },
      { name: 'Fragmento Finalizador (Roxo)' },
      { name: 'Proteção contra Veneno (Roxo)' },
      { name: 'Fragmento de Elemento III (Roxo)' },
      { name: 'Fragmento da Praga (Roxo)' },
      { name: 'Fragmento de Cristal (Roxo)' },
      { name: 'Proteção de Gelo (Roxo)' },
      { name: 'Fragmento da Chama Feroz (Roxo)' },
      { name: 'Fragmento Finalizador (Verde)' },
      { name: 'Proteção contra Veneno (Verde)' },
      { name: 'Fragmento de Elemento III (Verde)' },
      { name: 'Fragmento da Praga (Verde)' },
      { name: 'Fragmento de Cristal (Verde)' },
      { name: 'Proteção de Gelo (Verde)' },
      { name: 'Fragmento da Chama Feroz (Verde)' },
      { name: 'Fragmento da Fortaleza (Amarelo)' },
      { name: 'Fragmento Mágico (Amarelo)' },
      { name: 'Fragmento do Espírito Maligno (Amarelo)' },
      { name: 'Fragmento da Morte (Amarelo)' },
      { name: 'Fragmento de Desaparecimento (Amarelo)' },
    ],
    7: [
      { name: 'Fragmento de Melodia Venenosa (Vermelho)' },
      { name: 'Fragmento de Gelo Estilhaçado (Vermelho)' },
      { name: 'Fragmento de Espinho Venenoso (Roxo)' },
      { name: 'Fragmento de Estudo de Veneno (Roxo)' },
      { name: 'Fragmento de Ataque Venenoso (Roxo)' },
      { name: 'Fragmento de Elemento IV (Roxo)' },
      { name: 'Fragmento de Proteção de Gelo (Roxo)' },
      { name: 'Fragmento de Armadura Gélida (Roxo)' },
      { name: 'Fragmento Gelado (Roxo)' },
      { name: 'Fragmento de Espinho Venenoso (Verde)' },
      { name: 'Fragmento de Estudo de Veneno (Verde)' },
      { name: 'Fragmento de Ataque Venenoso (Verde)' },
      { name: 'Fragmento de Elemento IV (Verde)' },
      { name: 'Fragmento de Proteção de Gelo (Verde)' },
      { name: 'Fragmento de Armadura Gélida (Verde)' },
      { name: 'Fragmento Gelado (Verde)' },
      { name: 'Fragmento de Armadura Sagrada (Amarelo)' },
      { name: 'Fragmento de Armadura da Alma (Amarelo)' },
      { name: 'Fragmento de Soldado da Alma (Amarelo)' },
      { name: 'Fragmento de Destruição (Amarelo)' },
      { name: 'Fragmento de Batalha Feroz (Amarelo)' },
    ],
    8: [
      { name: 'Visão Aprimorada (Vermelho)' },
      { name: 'Mundo de Gelo (Vermelho)' },
      { name: 'Sussurro Maligno (Roxo)' },
      { name: 'Aprimoramento da Imagem Espelhada (Roxo)' },
      { name: 'Ressurreição do Veneno (Roxo)' },
      { name: 'Armadura de Veneno (Roxo)' },
      { name: 'Aprimoramento de Habilidade (Roxo)' },
      { name: 'Frio Cortante (Roxo)' },
      { name: 'Ressurreição do Gelo (Roxo)' },
      { name: 'Armadura de Gelo (Roxo)' },
      { name: 'Sussurro Maligno (Verde)' },
      { name: 'Aprimoramento da Imagem Espelhada (Verde)' },
      { name: 'Ressurreição do Veneno (Verde)' },
      { name: 'Armadura de Veneno (Verde)' },
      { name: 'Aprimoramento de Habilidade (Verde)' },
      { name: 'Frio Cortante (Verde)' },
      { name: 'Ressurreição do Gelo (Verde)' },
      { name: 'Armadura de Gelo (Verde)' },
      { name: 'Fragmento de Corpo Sagrado (Amarelo)' },
      { name: 'Fragmento de Ferida Divina (Amarelo)' },
      { name: 'Fragmento de Poder Antigo (Amarelo)' },
      { name: 'Fragmento de Separação de Alma (Amarelo)' },
      { name: 'Fragmento de Carnificina (Amarelo)' },
    ],
    9: [],
  };
