
export interface IdealRune {
    name: string;
    count: number;
  }
  
  export const IDEAL_RUNES_BY_TIER: Record<number, IdealRune[]> = {
    2: [
      { name: 'Fragmento de Maldição (Roxo)', count: 14 },
      { name: 'Fragmento do Pântano Venenoso (Roxo)', count: 14 },
      { name: 'Fragmento Inócuo (Roxo)', count: 14 },
      { name: 'Fragmento Venenoso (Roxo)', count: 14 },
      { name: 'Fragmento da Ira Celestial (Roxo)', count: 14 },
      { name: 'Fragmento de Congelar (Roxo)', count: 14 },
      { name: 'Fragmento de Transição (Roxo)', count: 14 },
      { name: 'Fragmento de Meteorito (Roxo)', count: 14 },
      { name: 'Fragmento de Maldição (Verde)', count: 14 },
      { name: 'Fragmento do Pântano Venenoso (Verde)', count: 14 },
      { name: 'Fragmento Inócuo (Verde)', count: 14 },
      { name: 'Fragmento Venenoso (Verde)', count: 14 },
      { name: 'Fragmento da Ira Celestial (Verde)', count: 14 },
      { name: 'Fragmento de Congelar (Verde)', count: 14 },
      { name: 'Fragmento de Transição (Verde)', count: 14 },
      { name: 'Fragmento de Meteorito (Verde)', count: 14 },
      { name: 'Fragmento de Sombra (Amarelo)', count: 14 },
      { name: 'Fragmento de Proteção (Amarelo)', count: 14 },
      { name: 'Fragmento de Artesão (Amarelo)', count: 14 },
      { name: 'Fragmento Inabalável (Amarelo)', count: 14 },
      { name: 'Fragmento de Ataque Poderoso (Amarelo)', count: 14 },
    ],
    3: [
      { name: 'Fragmento do Escudo de Veneno (Vermelho)', count: 14 },
      { name: 'Fragmento do Espaço-Tempo (Vermelho)', count: 14 },
      { name: 'Fragmento de Substituição (Roxo)', count: 14 },
      { name: 'Fragmento da Chama Venenosa (Roxo)', count: 14 },
      { name: 'Fragmento da Ilusão (Roxo)', count: 14 },
      { name: 'Fragmento de Explosão Venenosa (Roxo)', count: 14 },
      { name: 'Fragmento da Estrela Cadente (Roxo)', count: 14 },
      { name: 'Fragmento da Perdição (Roxo)', count: 14 },
      { name: 'Fragmento de Calor (Roxo)', count: 14 },
      { name: 'Fragmento do Ceifador (Roxo)', count: 14 },
      { name: 'Fragmento de Substituição (Verde)', count: 14 },
      { name: 'Fragmento da Chama Venenosa (Verde)', count: 14 },
      { name: 'Fragmento da Ilusão (Verde)', count: 14 },
      { name: 'Fragmento de Explosão Venenosa (Verde)', count: 14 },
      { name: 'Fragmento da Estrela Cadente (Verde)', count: 14 },
      { name: 'Fragmento da Perdição (Verde)', count: 14 },
      { name: 'Fragmento de Calor (Verde)', count: 14 },
      { name: 'Fragmento do Ceifador (Verde)', count: 14 },
      { name: 'Fragmento Guardião (Amarelo)', count: 14 },
      { name: 'Fragmento de Paixão (Amarelo)', count: 14 },
      { name: 'Fragmento de Transcendência (Amarelo)', count: 14 },
      { name: 'Fragmento de Golpe Crucial (Amarelo)', count: 14 },
      { name: 'Fragmento de Justiça (Amarelo)', count: 14 },
    ],
    4: [
      { name: 'Fragmento do Mensageiro (Vermelho)', count: 14 },
      { name: 'Fragmento de Separação (Vermelho)', count: 14 },
      { name: 'Fragmento de Imagem Espelhada (Roxo)', count: 14 },
      { name: 'Fragmento de Juramento (Roxo)', count: 14 },
      { name: 'Fragmento de Rastro de Veneno (Roxo)', count: 14 },
      { name: 'Fragmento de Elemento (Roxo)', count: 14 },
      { name: 'Fragmento do Penhasco de Gelo (Roxo)', count: 14 },
      { name: 'Território do Ceifador (Roxo)', count: 14 },
      { name: 'Fragmento de Congelamento (Roxo)', count: 14 },
      { name: 'Fragmento de Imagem Espelhada (Verde)', count: 14 },
      { name: 'Fragmento de Juramento (Verde)', count: 14 },
      { name: 'Fragmento de Rastro de Veneno (Verde)', count: 14 },
      { name: 'Fragmento de Elemento (Verde)', count: 14 },
      { name: 'Fragmento do Penhasco de Gelo (Verde)', count: 14 },
      { name: 'Território do Ceifador (Verde)', count: 14 },
      { name: 'Fragmento de Congelamento (Verde)', count: 14 },
      { name: 'Fragmento de Placa (Amarelo)', count: 14 },
      { name: 'Fragmento de Integridade (Amarelo)', count: 14 },
      { name: 'Fragmento de Incursão (Amarelo)', count: 14 },
      { name: 'Fragmento de Pulso (Amarelo)', count: 14 },
      { name: 'Fragmento de Reparação (Amarelo)', count: 14 },
    ],
    5: [
      { name: 'Fragmento de Prazer Perverso (Roxo)', count: 14 },
      { name: 'Fragmento de Gelo (Roxo)', count: 14 },
      { name: 'Fragmento de Imagem Espelhada (Roxo)', count: 14 },
      { name: 'Fragmento da Miragem (Roxo)', count: 14 },
      { name: 'Fragmento Elemental II (Roxo)', count: 14 },
      { name: 'Sequelas do Veneno (Roxo)', count: 14 },
      { name: 'Fragmento do Espinho de Gelo (Roxo)', count: 14 },
      { name: 'Fragmento do Campo de Neve (Roxo)', count: 14 },
      { name: 'Fragmento do Inverno Elemental (Roxo)', count: 14 },
      { name: 'Fragmento de Imagem Espelhada (Verde)', count: 14 },
      { name: 'Fragmento da Miragem (Verde)', count: 14 },
      { name: 'Fragmento Elemental II (Verde)', count: 14 },
      { name: 'Sequelas do Veneno (Verde)', count: 14 },
      { name: 'Fragmento do Espinho de Gelo (Verde)', count: 14 },
      { name: 'Fragmento do Campo de Neve (Verde)', count: 14 },
      { name: 'Fragmento do Inverno Elemental (Verde)', count: 14 },
      { name: 'Fragmento de Escudo Flexível (Amarelo)', count: 14 },
      { name: 'Fragmento de Armadura Flexível (Amarelo)', count: 14 },
      { name: 'Fragmento de Escudo Firme (Amarelo)', count: 14 },
      { name: 'Fragmento de Peixe de Ferro (Amarelo)', count: 14 },
      { name: 'Fragmento Base (Amarelo)', count: 14 },
    ],
    6: [
      { name: 'Fragmento de Iluminação (Roxo)', count: 14 },
      { name: 'Fragmento de Injeção (Roxo)', count: 14 },
      { name: 'Fragmento Finalizador (Roxo)', count: 14 },
      { name: 'Proteção contra Veneno (Roxo)', count: 14 },
      { name: 'Fragmento de Elemento III (Roxo)', count: 14 },
      { name: 'Fragmento da Praga (Roxo)', count: 14 },
      { name: 'Fragmento de Cristal (Roxo)', count: 14 },
      { name: 'Proteção de Gelo (Roxo)', count: 14 },
      { name: 'Fragmento da Chama Feroz (Roxo)', count: 14 },
      { name: 'Fragmento Finalizador (Verde)', count: 14 },
      { name: 'Proteção contra Veneno (Verde)', count: 14 },
      { name: 'Fragmento de Elemento III (Verde)', count: 14 },
      { name: 'Fragmento da Praga (Verde)', count: 14 },
      { name: 'Fragmento de Cristal (Verde)', count: 14 },
      { name: 'Proteção de Gelo (Verde)', count: 14 },
      { name: 'Fragmento da Chama Feroz (Verde)', count: 14 },
      { name: 'Fragmento da Fortaleza (Amarelo)', count: 14 },
      { name: 'Fragmento Mágico (Amarelo)', count: 14 },
      { name: 'Fragmento do Espírito Maligno (Amarelo)', count: 14 },
      { name: 'Fragmento da Morte (Amarelo)', count: 14 },
      { name: 'Fragmento de Desaparecimento (Amarelo)', count: 14 },
    ],
    7: [
      { name: 'Fragmento de Melodia Venenosa (Vermelho)', count: 14 },
      { name: 'Fragmento de Gelo Estilhaçado (Vermelho)', count: 14 },
      { name: 'Fragmento de Espinho Venenoso (Roxo)', count: 14 },
      { name: 'Fragmento de Estudo de Veneno (Roxo)', count: 14 },
      { name: 'Fragmento de Ataque Venenoso (Roxo)', count: 14 },
      { name: 'Fragmento de Elemento IV (Roxo)', count: 14 },
      { name: 'Fragmento de Proteção de Gelo (Roxo)', count: 14 },
      { name: 'Fragmento de Armadura Gélida (Roxo)', count: 14 },
      { name: 'Fragmento Gelado (Roxo)', count: 14 },
      { name: 'Fragmento de Espinho Venenoso (Verde)', count: 14 },
      { name: 'Fragmento de Estudo de Veneno (Verde)', count: 14 },
      { name: 'Fragmento de Ataque Venenoso (Verde)', count: 14 },
      { name: 'Fragmento de Elemento IV (Verde)', count: 14 },
      { name: 'Fragmento de Proteção de Gelo (Verde)', count: 14 },
      { name: 'Fragmento de Armadura Gélida (Verde)', count: 14 },
      { name: 'Fragmento Gelado (Verde)', count: 14 },
      { name: 'Fragmento de Armadura Sagrada (Amarelo)', count: 14 },
      { name: 'Fragmento de Armadura da Alma (Amarelo)', count: 14 },
      { name: 'Fragmento de Soldado da Alma (Amarelo)', count: 14 },
      { name: 'Fragmento de Destruição (Amarelo)', count: 14 },
      { name: 'Fragmento de Batalha Feroz (Amarelo)', count: 14 },
    ],
    8: [
      { name: 'Visão Aprimorada (Vermelho)', count: 14 },
      { name: 'Mundo de Gelo (Vermelho)', count: 14 },
      { name: 'Sussurro Maligno (Roxo)', count: 14 },
      { name: 'Aprimoramento da Imagem Espelhada (Roxo)', count: 14 },
      { name: 'Ressurreição do Veneno (Roxo)', count: 14 },
      { name: 'Armadura de Veneno (Roxo)', count: 14 },
      { name: 'Aprimoramento de Habilidade (Roxo)', count: 14 },
      { name: 'Frio Cortante (Roxo)', count: 14 },
      { name: 'Ressurreição do Gelo (Roxo)', count: 14 },
      { name: 'Armadura de Gelo (Roxo)', count: 14 },
      { name: 'Sussurro Maligno (Verde)', count: 14 },
      { name: 'Aprimoramento da Imagem Espelhada (Verde)', count: 14 },
      { name: 'Ressurreição do Veneno (Verde)', count: 14 },
      { name: 'Armadura de Veneno (Verde)', count: 14 },
      { name: 'Aprimoramento de Habilidade (Verde)', count: 14 },
      { name: 'Frio Cortante (Verde)', count: 14 },
      { name: 'Ressurreição do Gelo (Verde)', count: 14 },
      { name: 'Armadura de Gelo (Verde)', count: 14 },
      { name: 'Fragmento de Corpo Sagrado (Amarelo)', count: 14 },
      { name: 'Fragmento de Ferida Divina (Amarelo)', count: 14 },
      { name: 'Fragmento de Poder Antigo (Amarelo)', count: 14 },
      { name: 'Fragmento de Separação de Alma (Amarelo)', count: 14 },
      { name: 'Fragmento de Carnificina (Amarelo)', count: 14 },
    ],
    9: [],
  };
  
  // Lista de todas as runas para usar nos seletores
  export const ALL_RUNE_FRAGMENTS = [
    ...IDEAL_RUNES_BY_TIER[2].map(rune => rune.name),
    ...IDEAL_RUNES_BY_TIER[3].map(rune => rune.name),
    ...IDEAL_RUNES_BY_TIER[4].map(rune => rune.name),
    ...IDEAL_RUNES_BY_TIER[5].map(rune => rune.name),
    ...IDEAL_RUNES_BY_TIER[6].map(rune => rune.name),
    ...IDEAL_RUNES_BY_TIER[7].map(rune => rune.name),
    ...IDEAL_RUNES_BY_TIER[8].map(rune => rune.name)
  ].filter((value, index, self) => self.indexOf(value) === index); // Remove duplicatas
  